create_clock -name core_clk -period 250.000 [get_ports core_clk_i]
set_clock_uncertainty 0.200 [get_clocks core_clk]
set_input_delay 2.000 -clock core_clk [get_ports s_axil_*_i]
set_input_delay 2.000 -clock core_clk [get_ports s_axis_*_i]
set_input_delay 2.000 -clock core_clk [get_ports m_axis_tready_i]
set_output_delay 2.000 -clock core_clk [get_ports s_axil_*_o]
set_output_delay 2.000 -clock core_clk [get_ports s_axis_tready_o]
set_output_delay 2.000 -clock core_clk [get_ports m_axis_*_o]
set_output_delay 2.000 -clock core_clk [get_ports irq_o]
set_false_path -from [get_ports core_reset_n_i]
